(function(){
  'use strict';
  const API_BASE='https://www.runshi.top';
  const tokenKey='runshi_addin_session';
  const prompts={
    polish:'你是资深中文编辑。以最小改动修正错别字、语病、标点、指代不明和明显冗余。保留事实、数据、术语、引用、论断强度和作者语气。不要添加新信息，不要整句重写。直接输出润色后的完整文本，不要解释或使用 Markdown。',
    deai:'你是中文写作自然化编辑。减少机械连接词、重复句式和空泛套话，调整句子节奏，但必须保留事实、数据、术语、引用、论证结构和论断强度。不要承诺规避检测，不要添加新信息。直接输出修改后的完整文本，不要解释或使用 Markdown。'
  };
  let token=sessionStorage.getItem(tokenKey)||'';
  let snapshot=null;
  let changes=[];
  let busy=false;
  let capabilities={canWriteBack:false,canAnnotate:false,canTrackRevisions:false};
  function setBusy(value){busy=value;for(const id of ['analyzeButton','applyButton','acceptAllButton','logoutButton','taskMode']){const element=document.getElementById(id);if(element)element.disabled=value}document.querySelectorAll('.suggestion-actions button').forEach(button=>button.disabled=value)}
  const $=selector=>document.querySelector(selector);
  function setStatus(message,error=false){const el=$('#statusMessage');el.textContent=message||'';el.classList.toggle('error',error)}
  function showAuthenticated(ok){$('#loginView').hidden=ok;$('#appView').hidden=!ok}
  async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const res=await fetch(`${API_BASE}${path}`,{...options,headers,signal:AbortSignal.timeout(300000)});const body=await res.json().catch(()=>({}));if(!res.ok||body.ok===false){const e=new Error(body.error||`请求失败（${res.status}）`);e.status=res.status;throw e}return body}
  function renderAccount(data){const user=data?.user||data?.account||{};$('#accountName').textContent=user.displayName||user.email||'润石会员';const balance=user.creditBalance??user.creditsRemaining;$('#accountBalance').textContent=Number.isFinite(Number(balance))?`余额 ${Number(balance)} 积分`:''}
  function renderCapabilities(){const note=$('#reviewCapability');const apply=$('#applyButton');if(!capabilities.canWriteBack){note.innerHTML='<strong>当前仅提供面板建议</strong><span>当前宿主无法安全写回，确认后会复制结果供你手动粘贴。</span>';if(apply)apply.textContent='复制已选修订';return}if(apply)apply.textContent='写入原文修订';if(capabilities.canTrackRevisions&&capabilities.canAnnotate){note.innerHTML='<strong>原文批阅已开启</strong><span>建议可同步为批注；写回时保留原生修订，可在“审阅”中继续处理。</span>';return}note.innerHTML='<strong>安全写回可用</strong><span>当前版本不支持完整批注或原生修订，写入前仍会核对原文。</span>'}
  async function verifySession(){if(!token){showAuthenticated(false);return}try{const data=await api('/api/auth/me');renderAccount(data);showAuthenticated(true)}catch(error){if(error.status===401){token='';sessionStorage.removeItem(tokenKey);showAuthenticated(false);return}showAuthenticated(true);setStatus('暂时无法连接润石服务，请检查网络后重试。',true)}}
  function changeDescription(change){if(change.type==='replace')return{label:'替换',oldText:change.oldText,newText:change.newText};if(change.type==='delete')return{label:'删除',oldText:change.oldText,newText:'（删除）'};return{label:'补充',oldText:'（新增）',newText:change.newText}}
  function editableChanges(){return changes.filter(change=>change.type!=='equal')}
  function renderSuggestions(){const container=$('#suggestions');container.replaceChildren();const editable=changes.filter(c=>c.type!=='equal');$('#actionbar').hidden=editable.length===0;if(!editable.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='这段文字已经很好，没有发现必须修改的内容。';container.append(empty);return}for(const change of editable){const d=changeDescription(change);const card=document.createElement('article');card.className='suggestion';const header=document.createElement('header');const label=document.createElement('span');label.textContent=d.label;header.append(label);const old=document.createElement('p');const del=document.createElement('del');del.textContent=d.oldText;old.append(del);const next=document.createElement('p');const ins=document.createElement('ins');ins.textContent=d.newText;next.append(ins);const actions=document.createElement('div');actions.className='suggestion-actions';for(const [state,text] of [['accepted','接受'],['rejected','忽略']]){const button=document.createElement('button');button.type='button';button.disabled=busy;button.textContent=text;button.classList.toggle('active',change.status===state);button.addEventListener('click',()=>{change.status=state;renderSuggestions()});actions.append(button)}card.append(header,old,next,actions);container.append(card)}}
  async function analyze(){if(busy)return;setBusy(true);snapshot=null;changes=[];$('#suggestions').replaceChildren();$('#actionbar').hidden=true;setStatus('正在读取当前选区…');try{snapshot=await window.RunShiHost.captureSelection();if(!snapshot?.text?.trim())throw new Error('请先在文档中选中需要修改的文字。');if(snapshot.host==='word'&&!snapshot.bookmarkName){capabilities={...capabilities,canWriteBack:false,canAnnotate:false,canTrackRevisions:false};renderCapabilities()}if(snapshot.text.length>12000)throw new Error('单次最多处理 12,000 字，请分段选择。');$('#selectionPreview').textContent=snapshot.text;setStatus('正在生成修改建议…');const task=$('#taskMode').value;const data=await api('/api/ai/chat',{method:'POST',body:JSON.stringify({task,messages:[{role:'system',content:prompts[task]},{role:'user',content:snapshot.text}],options:{billableChars:snapshot.text.length,maxTokens:Math.min(8000,Math.max(512,Math.ceil(snapshot.text.length*1.8)))}})});const revised=String(data.content||'').trim();if(!revised)throw new Error('没有收到有效的修改结果，请稍后重试。');changes=window.RunShiDiff.compute(snapshot.text,revised);renderSuggestions();const editable=editableChanges();if(!editable.length){setStatus('未发现需要修改的内容。');return}let annotation=null;if(capabilities.canAnnotate&&typeof window.RunShiHost.annotateSuggestions==='function'){try{annotation=await window.RunShiHost.annotateSuggestions(snapshot,editable)}catch(error){annotation={ok:false,error:error.message}}}if(annotation?.ok){const warning=annotation.unresolved?(annotation.summaryIncluded?`，${annotation.unresolved} 处已收录在汇总批注中`:`；另有 ${annotation.unresolved} 处未能同步批注，请在面板查看`):'';setStatus(`已生成 ${editable.length} 处建议，并同步 ${annotation.annotated||0} 条原文批注${warning}。`)}else{setStatus(`已生成 ${editable.length} 处建议。${annotation?.error?`原文批注暂未同步：${annotation.error}`:''}`)}}catch(error){setStatus(error.message,true)}finally{setBusy(false)}}
  async function applyAccepted(){if(busy||!snapshot)return;const accepted=editableChanges().filter(change=>change.status==='accepted');const finalText=window.RunShiDiff.apply(changes);if(!accepted.length||finalText===snapshot.text){setStatus('尚未接受任何修改。',true);return}setBusy(true);try{if(!capabilities.canWriteBack){if(!navigator.clipboard?.writeText)throw new Error('当前宿主无法安全写回，也无法访问剪贴板。请在面板中手动复制建议。');await navigator.clipboard.writeText(finalText);setStatus('已复制包含所选修改的文本。当前宿主无法建立稳定定位，请回到原文手动粘贴。');return}const result=typeof window.RunShiHost.applyAcceptedChanges==='function'?await window.RunShiHost.applyAcceptedChanges(snapshot,accepted,finalText):await window.RunShiHost.replaceSelection(snapshot,finalText);if(result?.ok===false)throw new Error(result.error||'文档写入失败。');snapshot={...snapshot,text:finalText,end:Number.isFinite(snapshot.start)?snapshot.start+finalText.length:snapshot.end};changes=[];renderSuggestions();$('#selectionPreview').textContent=finalText;setStatus(result?.tracked===false?'已安全写回文档；当前编辑器版本不支持原生修订记录。':'已写入 Word/WPS 原文修订，可在「审阅/修订」中逐条接受或拒绝。')}catch(error){setStatus(error.message,true)}finally{setBusy(false)}}
  $('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget);$('#loginMessage').textContent='正在登录…';try{const data=await api('/api/auth/login-email',{method:'POST',body:JSON.stringify({email:String(form.get('email')||'').trim(),password:String(form.get('password')||'')})});token=data.token;sessionStorage.setItem(tokenKey,token);renderAccount(data);event.currentTarget.reset();$('#loginMessage').textContent='';showAuthenticated(true)}catch(error){$('#loginMessage').textContent=error.message}});
  $('#logoutButton').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}token='';sessionStorage.removeItem(tokenKey);showAuthenticated(false)});
  $('#analyzeButton').addEventListener('click',analyze);
  $('#acceptAllButton').addEventListener('click',()=>{for(const change of changes)if(change.type!=='equal')change.status='accepted';renderSuggestions()});
  $('#applyButton').addEventListener('click',applyAccepted);
  window.RunShiHost.ready().then(name=>{$('#hostName').textContent=name;capabilities=window.RunShiHost.capabilities?.()||capabilities;renderCapabilities();verifySession()}).catch(error=>{$('#hostName').textContent='编辑器连接失败';showAuthenticated(false);$('#loginMessage').textContent=error.message});
})();
