(function(global){
  'use strict';
  function trimCommon(a,b){let p=0;const m=Math.min(a.length,b.length);while(p<m&&a[p]===b[p])p++;let s=0;while(s<m-p&&a[a.length-1-s]===b[b.length-1-s])s++;return{prefix:a.slice(0,p),oldMiddle:a.slice(p,a.length-s),newMiddle:b.slice(p,b.length-s),suffix:s?a.slice(a.length-s):[]}}
  function lcs(a,b){const m=a.length,n=b.length,dp=Array.from({length:m+1},()=>new Uint32Array(n+1));for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)dp[i][j]=a[i-1]===b[j-1]?dp[i-1][j-1]+1:Math.max(dp[i-1][j],dp[i][j-1]);const ops=[];let i=m,j=n;while(i>0||j>0){if(i>0&&j>0&&a[i-1]===b[j-1]){ops.push({type:'equal',value:a[i-1]});i--;j--}else if(j>0&&(i===0||dp[i][j-1]>=dp[i-1][j])){ops.push({type:'insert',value:b[j-1]});j--}else{ops.push({type:'delete',value:a[i-1]});i--}}return ops.reverse()}
  function group(ops){const groups=[];for(const op of ops){const last=groups[groups.length-1];if(last&&last.type===op.type)last.text+=op.value;else groups.push({type:op.type,text:op.value})}return groups}
  function build(groups){const changes=[];let id=0;for(let i=0;i<groups.length;i++){const g=groups[i];if(g.type==='equal'){changes.push({id:id++,type:'equal',text:g.text})}else if(g.type==='delete'&&groups[i+1]?.type==='insert'){changes.push({id:id++,type:'replace',oldText:g.text,newText:groups[i+1].text,status:'pending'});i++}else if(g.type==='delete'){changes.push({id:id++,type:'delete',oldText:g.text,status:'pending'})}else{changes.push({id:id++,type:'insert',newText:g.text,status:'pending'})}}return changes}
  function addOffsets(changes){let offset=0;for(const change of changes){change.originalStart=offset;if(change.type==='equal')offset+=change.text.length;else if(change.type==='replace'||change.type==='delete')offset+=change.oldText.length;change.originalEnd=offset}return changes}
  function compute(oldText,newText){if(oldText===newText)return[];const a=Array.from(oldText),b=Array.from(newText),t=trimCommon(a,b);const ops=[...t.prefix.map(value=>({type:'equal',value}))];if(!t.oldMiddle.length)ops.push(...t.newMiddle.map(value=>({type:'insert',value})));else if(!t.newMiddle.length)ops.push(...t.oldMiddle.map(value=>({type:'delete',value})));else if(t.oldMiddle.length*t.newMiddle.length>1000000){ops.push(...t.oldMiddle.map(value=>({type:'delete',value})),...t.newMiddle.map(value=>({type:'insert',value})))}else ops.push(...lcs(t.oldMiddle,t.newMiddle));ops.push(...t.suffix.map(value=>({type:'equal',value})));return addOffsets(build(group(ops)))}
  function apply(changes){return changes.map(c=>c.type==='equal'?c.text:c.type==='replace'?(c.status==='accepted'?c.newText:c.oldText):c.type==='delete'?(c.status==='accepted'?'':c.oldText):(c.status==='accepted'?c.newText:'')).join('')}
  global.RunShiDiff={compute,apply};
})(window);
