'use strict';

/**
 * Pre-configured AI provider presets.
 * All presets use OpenAI-compatible chat/completions format unless noted.
 */
const PRESETS = {
  together: {
    id: 'together',
    name: 'Together AI',
    description: '使用 Llama 3.3 70B 模型，需要填写自己的 API Key',
    apiUrl: 'https://api.together.xyz/v1',
    model: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    needsKey: true,
    providerType: 'openai',
    keyPlaceholder: 'sk-...',
    keyUrl: 'https://api.together.ai/settings/api-keys',
  },
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    description: '国产大模型，性价比极高，中文能力强',
    apiUrl: 'https://api.deepseek.com',
    model: 'deepseek-chat',
    needsKey: true,
    providerType: 'openai',
    keyPlaceholder: 'sk-...',
    keyUrl: 'https://platform.deepseek.com/api_keys',
  },
  'siliconflow-deepseek-v4-flash': {
    id: 'siliconflow-deepseek-v4-flash',
    name: 'DeepSeek V4-Flash（硅基流动）',
    description: 'DeepSeek-V4 系列预览版 MoE 模型，284B 总参数 / 13B 激活，1M 上下文，由硅基流动托管',
    apiUrl: 'https://api.siliconflow.cn/v1',
    model: 'deepseek-ai/DeepSeek-V4-Flash',
    needsKey: true,
    providerType: 'openai',
    keyPlaceholder: 'sk-...',
    keyUrl: 'https://cloud.siliconflow.cn/account/ak',
  },
  'siliconflow-kimi-k2-6-pro': {
    id: 'siliconflow-kimi-k2-6-pro',
    name: 'Kimi K2.6 Pro（硅基流动）',
    description: '月之暗面 Kimi K2.6 原生多模态智能体模型 Pro 通道，256K 上下文，硅基流动托管',
    apiUrl: 'https://api.siliconflow.cn/v1',
    model: 'Pro/moonshotai/Kimi-K2.6',
    needsKey: true,
    providerType: 'openai',
    keyPlaceholder: 'sk-...',
    keyUrl: 'https://cloud.siliconflow.cn/account/ak',
  },
  'siliconflow-kimi-k2-6': {
    id: 'siliconflow-kimi-k2-6',
    name: 'Kimi K2.6（硅基流动）',
    description: 'Kimi K2.6 常规通道，价格更低、限速更严，硅基流动托管',
    apiUrl: 'https://api.siliconflow.cn/v1',
    model: 'moonshotai/Kimi-K2.6',
    needsKey: true,
    providerType: 'openai',
    keyPlaceholder: 'sk-...',
    keyUrl: 'https://cloud.siliconflow.cn/account/ak',
  },
  doubao: {
    id: 'doubao',
    name: '豆包（字节跳动）',
    description: '火山引擎 API，需要使用接入点 ID 作为模型名',
    apiUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    model: 'doubao-1.5-pro-32k',
    needsKey: true,
    providerType: 'openai',
    keyPlaceholder: '输入 API Key',
    keyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
  },
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    description: '使用 OpenAI 兼容接口，需要 Google AI API Key',
    apiUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    model: 'gemini-2.0-flash',
    needsKey: true,
    providerType: 'openai',
    keyPlaceholder: 'AIza...',
    keyUrl: 'https://aistudio.google.com/apikey',
  },
  claude: {
    id: 'claude',
    name: 'Claude（Anthropic）',
    description: '强大的推理与写作能力，使用原生 Anthropic API',
    apiUrl: 'https://api.anthropic.com',
    model: 'claude-sonnet-4-20250514',
    needsKey: true,
    providerType: 'anthropic',
    keyPlaceholder: 'sk-ant-...',
    keyUrl: 'https://console.anthropic.com/settings/keys',
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT-4o 等模型，支持所有 OpenAI 兼容接口',
    apiUrl: 'https://api.openai.com/v1',
    model: 'gpt-4o',
    needsKey: true,
    providerType: 'openai',
    keyPlaceholder: 'sk-...',
    keyUrl: 'https://platform.openai.com/api-keys',
  },
  ollama: {
    id: 'ollama',
    name: 'Ollama 本地模型',
    description: '完全离线运行，需先安装 Ollama 并下载模型',
    apiUrl: 'http://localhost:11434',
    model: 'qwen2.5',
    needsKey: false,
    providerType: 'ollama',
  },
  custom: {
    id: 'custom',
    name: '自定义接口',
    description: '手动填写 OpenAI 兼容接口地址',
    apiUrl: '',
    model: '',
    needsKey: true,
    providerType: 'openai',
    keyPlaceholder: '输入 API Key',
  },
};

const PRESET_ORDER = [
  'together',
  'deepseek',
  'siliconflow-deepseek-v4-flash',
  'siliconflow-kimi-k2-6-pro',
  'siliconflow-kimi-k2-6',
  'doubao',
  'gemini',
  'claude',
  'openai',
  'ollama',
  'custom',
];

module.exports = { PRESETS, PRESET_ORDER };
